### ISSUE TITLE
ออกแบบ UI front-end ในส่วนของ หน้า login

### ISSUE THREAD

**Issue by Jomsaruj** [Portus-NFT-Marketplace/Portus-Frontend#20]
ออกแบบ UI หน้า login ไม่ต้องใช้เวลามาก

- ช่องใส่ username, password
- ปุ่ม enter
- ไม่ต้องมี signup เพราะ ถือว่า foundation ต้องสมัครโดยตรงกับเรา สมัครเองไม่ได้

**Comment by PitchapaSaelim** [comment]
![image](https://user-images.githubusercontent.com/59871963/223427817-b9a22e69-aeef-458e-b1d3-ba1b06cd988d.png)

**Comment by PitchapaSaelim** [comment]
![image](https://user-images.githubusercontent.com/59871963/223431089-02ecad27-13f7-46a0-9347-5aad8e16effc.png)

**Comment by Jomsaruj** [comment]
LGTM
